#import = [
#	"~/.config/alacritty/themes/"
#]

[window]
dynamic_padding = false
padding = { x = 6, y = 6 }

[colors]
[colors.primary]
foreground = "#e4e8e9"
background = "#000000"

[font]
normal = { family = "PragmataPro", style = "Regular"}
bold =	{ family = "PragmataPro", style = "Bold"}
bold_italic = { family = "PragmataPro", style = "Bold Italic"}
italic = { family = "PragmataPro", style = "Italic"}
size = 15

[cursor]
style = { shape = "Block", blinking = "Off" }
